name: Knight_Plugin
version: 1.0.6
description: A plugin for Knight SMP
main: com.obsidian.knightsmp.KnightSmp
author: Blue Obsidian
website: https://knight-network.xyz/
github: https://github.com/Emmanuek5/
api-version: 1.19
softdepend: [UltimateAdvancementAPI,Essentials]
resources:
  playerdata.yml: true
permissions:
  feed:
    description: Feed a player
    default: op
  heal:
    description: Heals a player
    default: op
  select:
    description: Opens the selection screen
    default: op
  giveitem:
    description: Give a custom item to a player
    default: op
  farmtime:
    description: Farm Mobs
    default: op
  console:
    description: Console
    default: op
  player:
    description: Get a player's data
    default: op
    children:
      info:
        description: Get a player's info
        default: op
      reset-captcha:
       description: Captcha
       default: op
  ban-player:
    description: Ban a player
    default: op
  powers:
    description: Powers
    default: true
  ddroppeditems:
    description: See the items that where dropped on the ground
    default: true
  password:
    description: Password
    default: true
commands:
  heal:
    description: Heals a player to max health
    usage: /<command> [player]
    permission: knightsmp.heal
    aliases:
      - hm
      - healme
  feed:
    description: Feed a player
    usage: /<command> [player]
    permission: knightsmp.feed
    aliases:
      - feedme
      - fm
  farmtime:
    description: Farm Mobs
    usage: /<command> [mob] [amount]
    permission: knightsmp.farmtime
    aliases:
      - farmmob
  giveitem:
    description: Give a custom item to a player
    usage: /<command> [item] [player]
    permission: knightsmp.giveitem
    aliases:
      - giveitem
      - gi
  select:
    description: Opens the selection screen
    usage: /<command>
    permission: knightsmp.select
    aliases:
      - select
      - sl
  player:
    description: Get a player's data
    usage: /<command> [info] [player]
    permission: knightsmp.player
    aliases:
      - player
      - pl
      - player
  droppeditems:
    description: Dropped Items
    usage: /<command>
    permission: knightsmp.droppeditems
    aliases:
      - dippeditems
      - di
  download-latest-version:
    description: Download Latest Version
    usage: /<command>
    permission: knightsmp.console
    aliases:
      - download-latest-version
      - dlv
  ban-player:
    description: Ban a player
    usage: /<command> [player] [reason] [expiry] [isPermanent]
    permission: knightsmp.ban-player
    aliases:
      - ban-player
      - bp
      - ban
  turn-off-powers:
    description: Turn off powers
    usage: /<command>
    permission: knightsmp.powers
    aliases:
      - turn-off-powers
      - tofp
  turn-on-powers:
    description: Turn on powers
    usage: /<command>
    permission: knightsmp.powers
    aliases:
      - turn-on-powers
      - tofp
